# 内嵌tomcat线程最大数量，默认是200； 内存优化
server.tomcat.max-threads: 10

spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: com_jiuhuan_user
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
    

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: routes,env